steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "Dockerfile.tasks"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}"
      - "."
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}"
substitutions:
  _REGION: "europe-west2"
  _ARTIFACT_REPOSITORY: "delivery-pipeline"
  _IMAGE_NAME: "delivery-task-worker"
  _IMAGE_TAG: "latest"
